import Head from "next/head";
import Image from "next/image";

import {
  ArrowLeftIcon,
  EllipsisVerticalIcon,
  LockClosedIcon,
  PhoneIcon,
  VideoCameraIcon,
} from "@heroicons/react/24/solid";
import { useState } from "react";

type ChatMessage = {
  id: string;
  from: string;
  to: string;
  time: Date;
  message: string;
  seen: boolean;
};

export function MessageApp() {
  const thisuser = "Chloe";
  const otheruser = "Brian";

  const [chats, chats_update] = useState<ChatMessage[]>([
    {
      id: "y21839u21389",
      from: thisuser,
      to: otheruser,
      message: "How was last night?",
      seen: true,
      time: new Date(),
    },
    {
      id: "hfd4839ufhjuoi4",
      from: otheruser,
      to: thisuser,
      message: "It was crazy",
      seen: true,
      time: new Date(),
    },
  ]);

  const [message, messsage_update] = useState<string>("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#14b9c5] to-[#af2772] p-8">
        <div className="overflow-hidden rounded-2xl  bg-orange-50 shadow-xl">
          {/* TOP GREEN BAR */}

          <div className="flex flex-row gap-2 bg-green-700 p-2 ">
            <ArrowLeftIcon className="h-8 w-8 text-white" />

            <div className="h-10 w-10 overflow-hidden rounded-full">
              <Image
                src={"/assets/images/girl.jpeg"}
                width={100}
                height={100}
                alt="girl"
              />
            </div>

            <div className="flex-1">
              <h3 className="text-2xl font-normal text-white">Chloe</h3>
              <span className="text-white">last seen today 9:29 AM</span>
            </div>

            <VideoCameraIcon className="h-8 w-8 text-white" />
            <PhoneIcon className="h-8 w-8 text-white" />
            <EllipsisVerticalIcon className="h-8 w-8 text-white" />
          </div>
          <div className="mt-2 flex w-full">
            <span className="m-auto flex rounded-sm border-blue-200 bg-blue-200 p-1 text-center">
              7 August 2020
            </span>
          </div>
          <div className=" mt-4 flex w-full">
            <span className="text_center m-auto flex rounded-md border-yellow-100 bg-yellow-100 p-4 shadow-sm">
              <LockClosedIcon className="text-grey flex h-4 w-4" /> Messages and
              calls and end-to-end encrypted. No one outside of this chat,not
              even WhatsApp,can read or listen to them.Tap to learn more.{" "}
            </span>
          </div>

          {chats.map((chat) => {
            if (chat.from == otheruser) {
              return (
                <div
                  key={chat.id}
                  className="mt-6 flex  w-full flex-row justify-end"
                >
                  <span className="rounded-xl border-lime-200 bg-lime-200 p-3 text-right shadow-md ">
                    {chat.message}
                  </span>
                </div>
              );
            }

            return (
              <div key={chat.id} className="mt-6 w-full flex-row">
                <span className="m-auto rounded-xl border-white bg-white p-3 shadow-md">
                  {chat.message}
                </span>
              </div>
            );
          })}

          {/* <div className="mt-6 flex w-full flex-row justify-end">
            <span className="flex rounded-xl border-lime-200 bg-lime-200 p-3 text-right shadow-md">
              <ArrowUpCircleIcon className="text-grey-100 h-4 w-4" />
              Photo
            </span>
          </div> */}

          <div className=" flex flex-row gap-1 p-1">
            <input
              className=" flex-1 rounded-2xl border bg-white p-4 shadow-xl"
              value={message}
              onChange={(e) => {
                messsage_update(e.target.value);
              }}
            />
            <button
              className="rounded-xl border bg-green-800 px-4 text-white"
              onClick={() => {
                console.log("ClICKE!");
                console.log(message);

                const newchatmessage: ChatMessage = {
                  id: crypto.randomUUID(),
                  from: thisuser,
                  to: otheruser,
                  message,
                  seen: false,
                  time: new Date(),
                };

                chats_update([...chats, newchatmessage]);
              }}
            >
              SEND
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
