import Head from "next/head";
import Image from "next/image";

import {
  ArrowLeftIcon,
  LockClosedIcon,
  VideoCameraIcon,
} from "@heroicons/react/24/solid";
import { useState } from "react";
import {HiDotsVertical} from "react-icons/hi"
import {BsBatteryFull, BsFillTelephoneFill} from "react-icons/bs"
import {IoMdSend} from "react-icons/io"
import { FaSignal } from "react-icons/fa";
import { MdOutlineWifi } from "react-icons/md";

type ChatMessage = {
  id: string;
  from: string;
  to: string;
  time: Date;
  message: string;
  seen: boolean;
};

export function MessageApp() {
  const thisuser = "Chloe";
  const otheruser = "Brian";

  const [chats, chats_update] = useState<ChatMessage[]>([
    {
      id: "y21839u21389",
      from: thisuser,
      to: otheruser,
      message: "How was last night?",
      seen: true,
      time: new Date(),
    },
    {
      id: "hfd4839ufhjuoi4",
      from: otheruser,
      to: thisuser,
      message: "It was crazy",
      seen: true,
      time: new Date(),
    },
  ]);

  const [message, messsage_update] = useState<string>("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-sky-100 p-8">
        <div className="overflow-hidden border-2 border-black rounded-2xl h-fit w-80 bg-orange-50 shadow-xl">
        <div className="container p-1 px-3 flex flex-row bg-emerald-900 text-white ">
        <FaSignal className="h-4 w-4 mr-1"/>
        <p className="text-xs font-bold ">CellC</p>
        <MdOutlineWifi className=" ml-1 "/>
        <p className="text-xs justify-center mx-auto font-bold">9:41
        </p>
        <div className="flex flex-row ">
       <p className="text-xs font-bold">99%</p>
        <BsBatteryFull className="ml-1 "/>
        </div>
      </div>
          {/* TOP GREEN BAR */}

          <div className="flex flex-row gap-2 bg-emerald-800 p-2 ">
            <ArrowLeftIcon className="h-5 w-5 mt-4 text-white" />

            <div className="h-11 w-11 mt-1 overflow-hidden rounded-full">
              <Image
                src={"/assets/images/profilepic.png"}
                width={100}
                height={100}
                alt="girl"
              />
            </div>

            <div className="flex-1">
              <h3 className="text-xl font-normal text-white">Chloe</h3>
              <span className="text-white text-xs">last seen today 9:29 AM</span>
            </div>

<div className=" flex flex-row gap-2 pt-3">
            <VideoCameraIcon className="h-5 w-5 text-white" />
            <BsFillTelephoneFill className="h-4 w-4 mt-0.5 text-white" />
            <HiDotsVertical className="h-5 w-5 text-white" />
            </div>
          </div>
          <div className="mt-2 flex w-full">
            <span className="m-auto flex rounded-md text-sm bg-sky-200 p-2 text-center">
              7 August 2020
            </span>
          </div>
          <div className=" mt-2 flex w-full">
            <span className="text-center m-5 flex rounded-md bg-yellow-200 p-4 text-sm shadow-sm">
              <LockClosedIcon className="text-grey h-8 w-8 pb-4 mr-1" /> Messages and
              calls and end-to-end encrypted. No one outside of this chat not
              even WhatsApp can read or listen to them. Tap to learn more.{" "}
            </span>
          </div>

          {chats.map((chat) => {
            if (chat.from == otheruser) {
              return (
                <div
                  key={chat.id}
                  className="mt-6 flex w-full flex-row justify-end"
                >
                  <span className="rounded-xl border-lime-200 bg-lime-200 p-3 text-right shadow-md m-4">
                    {chat.message}
                  </span>
                </div>
              );
            }

            return (
              <div key={chat.id} className="mt-6 w-full flex-row pb-5">
                <span className="rounded-xl border-white bg-white p-3 shadow-md m-4">
                  {chat.message}
                </span>
              </div>
            );
          })}

          {/* <div className="mt-6 flex w-full flex-row justify-end">
            <span className="flex rounded-xl border-lime-200 bg-lime-200 p-3 text-right shadow-md">
              <ArrowUpCircleIcon className="text-grey-100 h-4 w-4" />
              Photo
            </span>
          </div> */}

          <div className=" flex flex-row gap-1 pb-5">
            <input
            placeholder="Type a message"
              className=" flex-1 rounded-3xl border bg-white p-4 shadow-xl ml-4"
              value={message}
              onChange={(e) => {
                messsage_update(e.target.value);
              }}
            />
            <button
              className="rounded-full border bg-emerald-800 px-4 text-white mr-4"
              onClick={() => {
                console.log("ClICKE!");
                console.log(message);

                const newchatmessage: ChatMessage = {
                  id: crypto.randomUUID(),
                  from: thisuser,
                  to: otheruser,
                  message,
                  seen: false,
                  time: new Date(),
                };

                chats_update([...chats, newchatmessage]);
              }}
            >
            <IoMdSend className="h-6 w-6"/>
            </button>
          </div>
        </div>

        <p className="text-gray-500 p-5">Type a message and send it !</p>
      </main>
    </>
  );
}
