import { useRef, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  MeshTransmissionMaterial,
  ContactShadows,
  Environment,
  OrbitControls,
  Html,
} from "@react-three/drei";
import { easing } from "maath";
import { useStore } from "./store";
import { Vector3 } from "three";
import { applyProps } from "@react-three/fiber/dist/declarations/src/core/utils";

export default function App() {
  return (
    <Canvas camera={{ position: [0, 0, 4], fov: 40 }}>
      <OrbitControls />
      <ambientLight intensity={0.7} />
      <spotLight
        intensity={0.5}
        angle={0.1}
        penumbra={1}
        position={[10, 15, -5]}
        castShadow
      />
      <Environment preset="city" background blur={1} />
      <ContactShadows
        resolution={512}
        position={[0, -0.8, 0]}
        opacity={1}
        scale={10}
        blur={2}
        far={0.8}
      />

      <Shoe rotation={[0.3, Math.PI / 1.6, 0]} />
      <Html transform position={[-0.4, 0.85, 0]} scale={0.5}>
        <h1>Nike Shoe</h1>
        <h1 className="font-bold text-red-700">R 599</h1>
      </Html>
    </Canvas>
  );
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nike_air_zoom_pegasus_36.glb --transform
Author: quaz30 (https://sketchfab.com/quaz30)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-zoom-pegasus-36-00fd99e778c244c3bd3b65f99dad7cb2
Title: Nike Air Zoom Pegasus 36
*/

function Shoe(props: any) {
  const { nodes, materials } = useGLTF(
    "/nike_air_zoom_pegasus_36-transformed.glb"
  ) as unknown as any;

  if (!nodes) return null;

  return (
    <group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.NikeShoe}
        {...props}
      />
    </group>
  );
}

useGLTF.preload("/nike_air_zoom_pegasus_36-transformed.glb");
