import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Alison&apos;s webpage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="h-screen bg-gradient-to-b from-purple-200 via-purple-200 to-pink-200">
          <div className="flex h-20  gap-1 p-4">
            <Image
              height={100}
              width={100}
              src={"/assets/images/logo.png"}
              className="h-14 w-14 rounded-xl pb-1 shadow-xl "
              alt={"logo"}
            />
            <div className="text-md border-l border-purple-700 pl-2 pt-2 font-mono">
              Web Developer
            </div>
          </div>
          <div className=" container mx-auto flex flex-row  px-56 py-20">
            <div className=" mr-5 flex border-4 border-purple-200 border-r-purple-500 p-6 pl-10 ">
              <p className="mt-40 font-serif text-3xl">
                Hi...
                <br />
                my name is Alison Buys ...
              </p>
            </div>

            <div className="container flex w-80  flex-col rounded-lg bg-purple-100 ">
              <div className="px-5 py-5">
                <Image
                  height={200}
                  width={300}
                  src={"/assets/images/photo.jpg"}
                  className=" rounded-lg pb-1 "
                  alt={"sunset"}
                />
                <p className="font-serif">
                  {" "}
                  Outgoing and ambitious high school graduate.
                  <br /> Problem solver eager to prove my value and talent.
                  <br /> Desire to learn and use my programing skills to work as
                  an software developer.
                  <br /> Motivated to advance and expand my skill set through
                  targeted mentorship and challenging projects.
                </p>
                <p className="pt-1 text-xs text-purple-500">
                  Mossel Bay, Western Cape
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

// function ProjectThumbnailLinks(props: {
//   link: string;
//   name: string;
//   description: string;
// }) {
//   return (
//     <Link href={props.link} className="">
//       <div className="h-full rounded-lg bg-gray-300 p-4 pb-4 transition hover:bg-purple-300">
//         <h3 className="font-serif text-purple-700">{props.name}</h3>

//         <div className="font-serif">{props.description}</div>
//       </div>
//     </Link>
//   );
// }

export default Home;
