import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className=" h-screen bg-gradient-to-b from-white via-purple-200 to-pink-200">
        <main className="">
          <div className="flex justify-center p-6 pl-10 font-serif text-3xl">
            Hi, my name is Alison Buys ...
          </div>
          <div className="flex h-20 justify-center gap-1 p-4">
            <Image
              height={100}
              width={100}
              src={"/assets/images/logo.png"}
              className="h-14 w-14 rounded-xl pb-1 shadow-xl "
              alt={"logo"}
            />
            <div className="text-md border-l border-purple-700 pl-2 pt-2 font-mono">
              Web Developer
            </div>
          </div>
          {/* <div className="flex justify-center pb-5 pt-5">
            <Image
              height={800}
              width={900}
              src={"/assets/images/code.webp"}
              className="rounded-xl shadow-xl shadow-indigo-950"
              alt={"code picture"}
            />
          </div> */}
          <div className="">
            <div className="flex justify-center pb-4 pt-4">
              <Image
                height={200}
                width={200}
                src={"/assets/images/photo.jpg"}
                className="rounded-full border-4 border-purple-500 shadow-xl"
                alt={"a picture of myself"}
              />
            </div>

            <div className="flex justify-center pt-5 text-center font-serif text-lg">
              Outgoing and ambitious high school graduate.
              <br /> Problem solver eager to prove my value and talent.
              <br /> Desire to learn and use my programing skills to work as an
              software developer.
              <br /> Motivated to advance and expand my skill set through
              targeted mentorship and challenging projects.
            </div>
          </div>
        </main>
      </body>
    </>
  );
};

// function ProjectThumbnailLinks(props: {
//   link: string;
//   name: string;
//   description: string;
// }) {
//   return (
//     <Link href={props.link} className="">
//       <div className="h-full rounded-lg bg-gray-300 p-4 pb-4 transition hover:bg-purple-300">
//         <h3 className="font-serif text-purple-700">{props.name}</h3>

//         <div className="font-serif">{props.description}</div>
//       </div>
//     </Link>
//   );
// }

export default Home;
