import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { BiTask } from "react-icons/bi";
import { FiTrash2 } from "react-icons/fi";
import  NewPostForm  from "~/components/newpostform";
import { api } from "~/utils/api";

export default function Home() {
  const initdb = api.example.initdb.useMutation();

  const listposts = api.example.listposts.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      
      <div className="p-2 text-3xl font-bold text-white mx-auto text-center"> TODO APP</div>
        <button
        className="p-2 rounded-md m-1 font-bold text-lg bg-pink-500 mx-6"
          onClick={() => {
            initdb.mutate(undefined, {
              onSuccess: (data) => {
                console.log(data);
              },
            });
          }}
        >
          Init DB
        </button>

        <NewPostForm />

        {listposts.data?.posts.map((post) => (
          <div key={post.id} className="rounded bg-pink-400 p-4 text-white m-4">
            <span className="text-2xl font-bold">{post.title}</span>
            <p>{post.content}</p>
            <div className="flex my-2 gap-2">
            <FiTrash2 className="h-8 w-8 bg-slate-300 p-2 bg-opacity-25 rounded-full  hover:bg-pink-300"></FiTrash2>{" "}
            <BiTask className="h-8 w-8 bg-slate-300 p-2 bg-opacity-25 rounded-full hover:bg-pink-300"></BiTask>{" "}
            </div>
            
          </div>
        ))}
      
      </main>
    </>
  );
}



// export default function TestPage() {
//   return (
//     <div>
//       TESTS
//       <div className="bg-green-500 sm:bg-blue-500 md:bg-yellow-500 lg:bg-orange-500 xl:bg-purple-500">
//         TEST
//       </div>
//     </div>
//   );
// }