import Head from "next/head";
import Image from "next/image";
import { BsCloudArrowUpFill, BsPersonLock, BsStarFill } from "react-icons/bs";
import { IoIosPeople } from "react-icons/io";

export function DesignApp() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <div className="h-screen w-48 rounded-l-md bg-blue-900 p-7">
          <div className="flex justify-center pb-5 pt-5">
            <Image
              height={100}
              width={100}
              src={"/assets/images/avatar.jpeg"}
              className=" h-14 w-14 rounded-full border-2 border-white "
              alt={"logo"}
            />
          </div>
          <div className="flex auto-cols-max flex-col gap-7 py-5 text-sm font-semibold text-white">
            <div className="flex gap-1 hover:bg-blue-950">
              <BsPersonLock className="h-5 w-5" />
              My cloud
            </div>
            <div className="flex gap-1 hover:bg-blue-950">
              <IoIosPeople className="h-5 w-5" />
              Shared files
            </div>
            <div className="flex gap-1 hover:bg-blue-950">
              <BsStarFill className="h-4 w-4" />
              Favorites
            </div>
            <div className="flex gap-1 hover:bg-blue-950">
              <BsCloudArrowUpFill className="h-5 w-5" /> Upload files
            </div>
            <div className="flex gap-1 hover:bg-blue-950">Settings</div>
            <div className="flex gap-1 hover:bg-blue-950">Log out</div>
          </div>
        </div>
        <div className="h-screen w-5/6 rounded-r-md bg-sky-50 "></div>
      </main>
    </>
  );
}
