import Head from "next/head";

export function DesignApp() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-auto bg-gradient-to-b from-indigo-600 via-purple-700 to-violet-500 "></main>
    </>
  );
}
